image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: ${REGISTRY_HOST}/${CI_PROJECT_NAME}

stages:
  - build
  - test

.build:
  stage: build
  script:
    - docker build -f ${DOCKERFILE} .

build:
  extends: .build
  environment:
    name: test
  before_script:
    - export DOCKERFILE=${CI_PROJECT_DIR}/Dockerfile

build_dev:
  extends: .build
  before_script:
    - export DOCKERFILE=${CI_PROJECT_DIR}/Dockerfile.develop
  environment:
    name: development
  only:
    refs:
      - develop

test:
  stage: test
  script:
    - docker build -f Dockerfile.test .

