version: "3"
services:
  dotnetapp:
    container_name: "dotnetapp"
    build: .
    ports: 
      - "80:80"
    networks:
      - bp_network
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27272:27017"
    networks:
      - bp_network
  rabbit:
    container_name: rabbit
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    hostname: rabbit
    ports:
      - 5672:5672
    restart: always
    image: rabbitmq
    networks:
      - bp_network
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
networks:
  bp_network: